# Generated by Django 3.1.2 on 2021-02-14 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=250)),
                ('problem_statement', models.TextField(max_length=5000)),
                ('problem_statement_image', models.ImageField(blank=True, null=True, upload_to='C:\\Users\\jbhol\\Desktop\\MathPrepPro\\deployment\\MathPrepPro\\static\\images\\problems\\')),
                ('problem_solution', models.CharField(max_length=500)),
                ('problem_type', models.CharField(max_length=250)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('problem_solution_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_number', models.IntegerField(default=1)),
                ('pro', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
